#include <nui/core.hpp>
#include <nui/window.hpp>

// This file is generated by nui.
#include <index.hpp>
#include <stdexcept>

int main() {
  using namespace Nui;

  std::runtime_error

      Window window{Nui::WindowOptions{
          .title = "Nui",
          .debug = true /* may open dev tools */,
      }};
  window.setSize(480, 320, WebViewHint::WEBVIEW_HINT_NONE);
  window.setHtml(index());
  window.run();
}